# Section 1:  NumPy Solutions

### Import the library with alias np

In [1]:
import numpy as np

####  1. Create an array of  8 eights

In [5]:
array=np.ones(8)*8
print(array)

[8. 8. 8. 8. 8. 8. 8. 8.]


#### 2. Create an array of the integers from 10 to 50

In [6]:
array=np.arange(10,51)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### 3. Create a 3x3 matrix with values ranging from 22 to 30

In [7]:
mat=np.arange(22,31)
print(mat.reshape(3,3))

[[22 23 24]
 [25 26 27]
 [28 29 30]]


## Indexing
Use below Array 'arr' for Questions below. 

Use Indexing to get the answer

In [17]:
arr=np.arange(26,51).reshape(5,5)
print(arr)

[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


#### 4. Use indexing on arr to get below output

       [[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]]

In [18]:
print(arr[2:,1:])

[[37 38 39 40]
 [42 43 44 45]
 [47 48 49 50]]


#### 5. Use indexing on arr to get below output
Output should be 50

In [19]:
print(arr[4,4])

50


#### 6. Use indexing on arr to get below output
      [[27],
       [32],
       [37]]

In [21]:
print(arr[0:3,1:2])

[[27]
 [32]
 [37]]


#### 7. Use indexing on arr to get below output
      [46, 47, 48, 49, 50]

In [25]:
print(arr[-1])

[46 47 48 49 50]


#### 8. Use indexing on arr to get below output
     [[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]]

In [28]:
arr[3:]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

### NumPy  Stats Functions

Use below given array 'arr'

In [30]:
arr=np.arange(26,51).reshape(5,5)
print(arr)

[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


#### 9. Find the sum of all the values in given array 'arr'

In [32]:
s=np.sum(arr)
print(s)

950


#### 10. Find the standard deviation of the values in given array 'arr'

In [33]:
print(np.std(arr))

7.211102550927978


#### 11.  Find the mean of all the values in given array 'arr'

In [34]:
print(np.mean(arr))

38.0


# Section 2: Pandas Solutions

#### Import pandas library  with alias pd

In [3]:
import pandas as pd

#### Read the given csv file

In [4]:
df=pd.read_csv('sales.csv',index_col=0)

### 1. What are the unique values in  the column "Parking"?

In [5]:
df['Parking'].unique()

array(['Open', 'Not Provided', 'Covered', 'No Parking'], dtype=object)

### 2. What is the mean store area of the given data? 

In [6]:
print(df['Store_Area'].mean())

1511.862554112554


### 3.What are the different columns available in the dataset?

In [7]:
df.columns

Index(['Dist_Taxi', 'Dist_Market', 'Dist_Metro', 'Store_Area',
       'Items_Available', 'Parking', 'Coupon_Category', 'Daily_Customer_Count',
       'Store_Sales'],
      dtype='object')

### 4. Create a new series (series1) with only the values of third row

In [8]:
series1=df.iloc[2]
series1

Dist_Taxi                      11001
Dist_Market                    14399
Dist_Metro                     16991
Store_Area                      1340
Items_Available                 1609
Parking                 Not Provided
Coupon_Category                CAT A
Daily_Customer_Count             720
Store_Sales                    54010
Name: 3, dtype: object

### 5. Create a new dataframe(df_short which contain first 5 rows and two columns("Coupon_Category" and "Store_Sales")

In [16]:
df_short=df.loc[[0,1,2,3,4],['Coupon_Category','Store_Sales']]


KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

In [18]:
df_short=df.head(5)[["Coupon_Category","Store_Sales"]]
df_short

Coupon_Category  Store_Sales
Observation                             
1                     CAT B        66490
2                     CAT B        39820
3                     CAT A        54010
4                     CAT B        53730
5                     CAT B        46620

### 6. In dataframe df_short, replace the index with ["First Row","Second Row","Third Row", "Forth Row", "Fifth Row"]

In [19]:
df_short["Names"]=["First Row","Second Row","Third Row", "Forth Row", "Fifth Row"]
print(df_short)

df_short.set_index("Names",inplace=True)
df_short

            Coupon_Category  Store_Sales       Names
Observation                                         
1                     CAT B        66490   First Row
2                     CAT B        39820  Second Row
3                     CAT A        54010   Third Row
4                     CAT B        53730   Forth Row
5                     CAT B        46620   Fifth Row


Coupon_Category  Store_Sales
Names                                  
First Row            CAT B        66490
Second Row           CAT B        39820
Third Row            CAT A        54010
Forth Row            CAT B        53730
Fifth Row            CAT B        46620

### 7. Create a dataframe df2 fulfilling the given conditions - Dist_Metro>18000 and Parking= Open

In [20]:
df2=df[(df["Dist_Metro"]>18000) & (df["Parking"]=="Open")]
df2

Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  Items_Available  \
Observation                                                                    
89             14306.0      12591.0     18029.0      1441.0           1723.0   
219            11195.0      16650.0     18762.0      1406.0           1677.0   
339             9308.0      18281.0     18532.0      1771.0           2147.0   
743            12973.0      15178.0     18836.0      1542.0           1844.0   
792            14470.0      14517.0     18178.0      1645.0           1963.0   
931            15082.0      14700.0     19617.0      1299.0           1560.0   

            Parking Coupon_Category  Daily_Customer_Count  Store_Sales  
Observation                                                             
89             Open           CAT B                   330        57860  
219            Open           CAT A                   480        61660  
339            Open           CAT C                   430        62710  
743            Open           CAT B                   680        51380  
792            Open           CAT C                   900        47300  
931            Open           CAT B                   770        96610

### 8.What is the minimum store sales and the standard Deviation of store sales.

In [21]:
print(df['Store_Sales'].min())
print(df['Store_Sales'].std())

300
50253.6390220453


### 9. Group the dataset with respect to the variable 'Coupon_Category' using aggregation function mean()

In [22]:
print(df.groupby('Coupon_Category').mean())

                   Dist_Taxi   Dist_Market    Dist_Metro   Store_Area  \
Coupon_Category                                                         
CAT A            8312.645062  11332.546296  13253.390244  1471.070769   
CAT B            8101.061453  10713.675978  12880.435616  1565.709945   
CAT C            8310.729958  11050.603376  13116.163866  1485.552743   

                 Items_Available  Daily_Customer_Count   Store_Sales  
Coupon_Category                                                       
CAT A                1762.845679            796.018237  73998.662614  
CAT B                1831.016760            782.958904  59191.479452  
CAT C                1784.170213            775.168067  45205.504202  


### 10. Drop the variable 'Parking' from the data.

In [24]:
df_1=df.drop('Parking',axis=1)
df_1

Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  Items_Available  \
Observation                                                                    
1               9796.0       5250.0     10703.0      1659.0           1961.0   
2               8294.0       8186.0     12694.0      1461.0           1752.0   
3              11001.0      14399.0     16991.0      1340.0           1609.0   
4               8301.0      11188.0     12289.0      1451.0           1748.0   
5              10510.0      12629.0     13921.0      1770.0           2111.0   
...                ...          ...         ...         ...              ...   
928            12176.0       8518.0     15673.0      1582.0           1910.0   
929             7214.0       8717.0     10553.0      1387.0           1663.0   
930             7423.0      11708.0     13220.0      1200.0           1436.0   
931            15082.0      14700.0     19617.0      1299.0           1560.0   
932             9297.0      12537.0     14418.0      1174.0           1429.0   

            Coupon_Category  Daily_Customer_Count  Store_Sales  
Observation                                                     
1                     CAT B                   530        66490  
2                     CAT B                   210        39820  
3                     CAT A                   720        54010  
4                     CAT B                   620        53730  
5                     CAT B                   450        46620  
...                     ...                   ...          ...  
928                   CAT C                  1080        66390  
929                   CAT A                   850        82080  
930                   CAT A                  1060        76440  
931                   CAT B                   770        96610  
932                   CAT C                  1110        54340  

[932 rows x 8 columns]

### 11. Export the Q10 dataframe without the 'Parking' column into a csv file.

In [62]:
df_1.to_csv('df1.csv',index=True)

# Question on some additional functions

###  Display the first 10 entries of the dataset.  (Hint-use function head())

In [63]:
df.head(10)

Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  Items_Available  \
Observation                                                                    
1               9796.0       5250.0     10703.0      1659.0           1961.0   
2               8294.0       8186.0     12694.0      1461.0           1752.0   
3              11001.0      14399.0     16991.0      1340.0           1609.0   
4               8301.0      11188.0     12289.0      1451.0           1748.0   
5              10510.0      12629.0     13921.0      1770.0           2111.0   
6               6665.0       5142.0      9972.0      1442.0           1733.0   
7              13153.0      11869.0     17811.0      1542.0           1858.0   
8               5882.0       9948.0     13315.0      1261.0           1507.0   
9               7495.0      11589.0     13370.0      1090.0           1321.0   
10              8233.0       7067.0     11400.0      1030.0           1235.0   

                  Parking Coupon_Category  Daily_Customer_Count  Store_Sales  
Observation                                                                   
1                    Open           CAT B                   530        66490  
2            Not Provided           CAT B                   210        39820  
3            Not Provided           CAT A                   720        54010  
4                 Covered           CAT B                   620        53730  
5            Not Provided           CAT B                   450        46620  
6                    Open           CAT B                   760        45260  
7              No Parking           CAT A                  1030        72240  
8                    Open           CAT C                  1020        37720  
9            Not Provided           CAT B                   680        46310  
10                   Open           CAT C                  1130        44150

###  Display the last 5 entries of the dataset.(Hint- use function tail())

In [64]:
df.tail(5)

Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  Items_Available  \
Observation                                                                    
928            12176.0       8518.0     15673.0      1582.0           1910.0   
929             7214.0       8717.0     10553.0      1387.0           1663.0   
930             7423.0      11708.0     13220.0      1200.0           1436.0   
931            15082.0      14700.0     19617.0      1299.0           1560.0   
932             9297.0      12537.0     14418.0      1174.0           1429.0   

             Parking Coupon_Category  Daily_Customer_Count  Store_Sales  
Observation                                                              
928          Covered           CAT C                  1080        66390  
929             Open           CAT A                   850        82080  
930             Open           CAT A                  1060        76440  
931             Open           CAT B                   770        96610  
932          Covered           CAT C                  1110        54340

### How many rows and columns are present in the dataset? (Hint- Use function shape)

In [25]:
print(df.shape)


(932, 9)


###  What are the different data types of the variables in the given dataset? (Hint- Use function info())

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 932 entries, 1 to 932
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Dist_Taxi             919 non-null    float64
 1   Dist_Market           919 non-null    float64
 2   Dist_Metro            931 non-null    float64
 3   Store_Area            924 non-null    float64
 4   Items_Available       917 non-null    float64
 5   Parking               932 non-null    object 
 6   Coupon_Category       932 non-null    object 
 7   Daily_Customer_Count  932 non-null    int64  
 8   Store_Sales           932 non-null    int64  
dtypes: float64(5), int64(2), object(2)
memory usage: 112.8+ KB


**Or you can use below command as well**

In [70]:
df.dtypes

Dist_Taxi               float64
Dist_Market             float64
Dist_Metro              float64
Store_Area              float64
Items_Available         float64
Parking                  object
Coupon_Category          object
Daily_Customer_Count      int64
Store_Sales               int64
dtype: object

# END